### ISSUE TITLE
Spoon on Google Cloud Test Labs

### ISSUE THREAD

**Issue by jd-alexander** [emmasuzuki/EspressoSpoonDemo#5]
I used this example to test out Spoon on Google Cloud Test Lab after finding it from your article on medium, so how did you get access to the assets/resources that spoon generated and is it a case where you have to use gcloud from the terminal to run the spoon command instead of just running tests via Android Studio?

**Comment by emmasuzuki** [comment]
If you are connecting to your local devices or emulators and want to see the spoon report, you do not need Google Cloud.  You can execute `./gradlew spoon` command at repo's root dir and spoon will generate all web format files (html, css, etc) under `app/build/spoon/{buildType}`.  You can open index.html in the dir and you will see something like https://cdn.rawgit.com/emmasuzuki/EspressoSpoonDemo/master/app/build/spoon/debug/index.html.

**Comment by jd-alexander** [comment]
Thanks for your response. Yes, i know that can be done for local devices, was wondering if the setup could work with google cloud devices as well.

**Comment by emmasuzuki** [comment]
Google Cloud has their own reporting.  I don't think you can plug in your own reporting config to Google Cloud.  Spoon's report is good for finding "WHAT went wrong", while Google Cloud's report is good for log purposes and its main feature is not reporting.  It is rather providing a mainstream device list so that you don't have to maintain and easy configuration for running multiple orientation/language/API version/devices variations. 

If you like to use Spoon report with CI, I would run spoon command on CI server and export it to some location which is accessible from a web server.

**Comment by jd-alexander** [comment]
Alright, makes alot of sense. Thanks for your feedback. Will use the CI approach for spoon and utilize other features from Google Cloud.
